-- This migration was originally authored for the hardened quota schema, but
-- its timestamp sorts before the migration that creates `app_settings` and
-- the quota helper functions. Keeping those statements here made a fresh
-- `supabase db reset` fail before it could reach the schema they target.
--
-- The later quota migration already creates the final, locked-down versions:
-- app_settings and quote_number_counters have RLS with no client policies;
-- quote_allowance and void_quote_usage are defined there with their final
-- grants. This deliberately remains a no-op so migration history is valid
-- when replayed in timestamp order.
